algoritmo "semnome"

var
 cont, numero: inteiro
 continuar: literal
inicio
 cont <- 1
 enquanto (cont<= 20)faca
  escreval(cont)
  cont <- cont + 1
 fimenquanto
 

 enquanto numero <> 2 faca
  escreval("Informe o numero: ")
  leia(numero)
fimenquanto


continuar<- "SIM"
enquanto continuar <> "NÃO" faca
  escreval("Deseja continuar SIM/NAO: ")
  leia(continuar)
fimenquanto
 
fimalgoritmo
